name: app_badge_plus
description: "A Flutter plugin for adding badges to your app icon."
version: 1.2.0
homepage: https://github.com/windows7lake/app_badge_plus

environment:
  sdk: ">=3.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  plugin:
    platforms:
      android:
        package: me.liolin.app_badge_plus
        pluginClass: AppBadgePlusPlugin
      ios:
        pluginClass: AppBadgePlusPlugin
      macos:
        pluginClass: AppBadgePlusPlugin
